### ISSUE TITLE
Does not support default parameters

### ISSUE THREAD

**Issue by josh-renton** [devrafalko/typeof-arguments#1]
Hi there, thank you for the package. I was just trying to implement it in my workflows and found that it doesn't support default arguments. Here is an example:

```
function foo (str, bool=false) {
    console.log(bool);
    typeOfArguments(arguments, [String, Boolean]);
}
```
Here is the output:

```
> foo('test')
false
TypeError: Invalid argument [1]. The [undefined] argument has been passed, while the argument of type [Boolean] is expected.
```
Is this something you're thinking to support in the future?

Thanks,

Josh

**Comment by devrafalko** [comment]
This package takes the `arguments` object as the parameter to validate the arguments' types. As I can see, the `arguments` object does not store any data of the default arguments' values `bool=false`, so I have no idea how I could support that feature.

You can alternatively use my other package [`typeof-properties`](https://www.npmjs.com/package/typeof-properties). It verifies the values' types the same way that the `typeof-arguments` does, except it takes the [Object] object rather than `arguments` object. 
You just have to create the object with all arguments manually and pass it through this package.
The default error message is quite different but it is changeable via callback function like below:
I hope that it's what you have expected.
```javascript
const typeOfProperties = require('typeof-properties');

function foo(str, bool = false) {
  const actual = { 0: str, 1: bool };
  const expected = { 0: String, 1: Boolean };
  typeOfProperties(actual, expected, (o) => {
    throw new TypeError(`Invalid argument [${o.name}]. The [${o.actual}] argument has been passed, while the argument of type [${o.expected}] is expected.`);
  });
}

foo('test');
```

**Comment by devrafalko** [comment]
Another way is to use `[Boolean, undefined]` as the expected type.

```javascript

const typeOfArguments = require('typeof-arguments');
function foo (str, bool=false) {
  console.log(bool);
  typeOfArguments(arguments, [String, [Boolean, undefined]]);
}
```
It expects `bool` to be `Boolean` or `undefined`.
If you pass `undefined`, the package does not throw any error and the `bool=false` default value is used.
If you pass `Boolean` value, package does not throw any error and this value is used.
If you pass any other than `Boolean` value, the package throws error.

**Comment by josh-renton** [comment]
Thank you for your response. I decided to write have a go at writing a function that handles adding the optional values to arguments. It's not pretty and it assumes all the optional args are at the end of the argument list, but it supports multiple optional arguments and suits my needs so I'll use it for now. If you're interested:

```javascript
const checkArgs = require('typeof-arguments');

function ask (arg1, arg2, bool=false, iLike='blue') {
    handleOptional(arguments, 2, [bool, iLike]);
    console.log(arguments);    
    checkArgs(arguments, [String, Number, Boolean, String]);
}

// typeof-arguments does not handle optional arguments, so we add them.
// Assumes optional arguments are after positional arguments.
// - _arguments: Incoming arguments from calling function
// - tryFromLen: arguments[index] of first optional argument.
//                e.g. 2 for (a, b, c=1, d=2)
// - valuesToAppend: The optional values missing from calling function's arguments.
function handleOptional (_arguments, tryFromLen, valuesToAppend) {
    const len = _arguments.length;
    const maxLen = tryFromLen + valuesToAppend.length;
    if (len < tryFromLen || len > maxLen) {
        // We are missing positional arguments, so just return
        // in this case just allow the return and typeof-arguments will
        // catch the missing earlier value.
        // OR
        // Function was passed too many arguments so don't worry.
        return;
    }
    // This loop won't run if arguments.length === maxLen
    const startAt = len - tryFromLen;
    let index = len;
    for (let i = startAt; i < valuesToAppend.length; i++) {
        const val = valuesToAppend[i];
        _arguments[index] = val;
        index++;
    }
}
```
